version: "3"
services:
  mysql:
    image: mysql:5.7.16
    container_name: mysql
    environment:
      MYSQL_DATABASE: gpbl_cowell
      MYSQL_ROOT_PASSWORD: password
    command: --secure-file-priv="" --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql_mode='STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,PIPES_AS_CONCAT'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
        - "3306:3306"