version: "3"
services:
  mysql:
    image: mysql:5.7.16
    container_name: mysql
    environment:
      MYSQL_DATABASE: gpbl_cowell
      MYSQL_ROOT_PASSWORD: password
      command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
        - "3306:3306"